package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	contentApp "blogThree/internal/content/app"
	apperr "blogThree/internal/errors"
	"blogThree/internal/interfaces/authctx"
	"blogThree/internal/interfaces/graph/model"
	"context"

	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	authorID, err := authctx.RequireUserID(ctx)
	if err != nil {
		return nil, err
	}

	post, err := r.ContentCmdSvc.CreatePost(ctx, authorID, input.Title, input.Body)
	if err != nil {
		return nil, err
	}
	return toPostModel(post), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := uuid.Parse(id)
	if err != nil {
		// sauber als VALIDATION-Fehler ausgeben (geht durch den ErrorPresenter)
		return nil, apperr.Validation("INVALID_POST_ID", "invalid post id", map[string]any{
			"id": id,
		})
	}

	p, err := r.ContentQrySvc.GetPost(ctx, postID)
	if err != nil {
		// Repo/Service liefern entweder DOMAIN (POST_NOT_FOUND) oder TECHNICAL – einfach durchreichen
		return nil, err
	}

	return toPostModel(p), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	// Defaults (Service clamped ohnehin, aber so ist's explizit)
	l := 20
	if limit != nil {
		l = int(*limit)
	}
	o := 0
	if offset != nil {
		o = int(*offset)
	}

	f := contentApp.PostListFilter{
		Limit:  l,
		Offset: o,
		// AuthorID: nil => alle Posts
	}

	posts, err := r.ContentQrySvc.ListPosts(ctx, f)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Post, 0, len(posts))
	for _, p := range posts {
		out = append(out, toPostModel(p))
	}
	return out, nil
}
