package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	contentApp "blogThree/internal/content/app"
	apperr "blogThree/internal/errors"
	"blogThree/internal/interfaces/authctx"
	"blogThree/internal/interfaces/graph"
	"blogThree/internal/interfaces/graph/model"
	"context"

	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	authorID, err := authctx.RequireUserID(ctx)
	if err != nil {
		return nil, err
	}

	post, err := r.ContentCmdSvc.CreatePost(ctx, authorID, input.Title, input.Body)
	if err != nil {
		return nil, err
	}

	return toPostModel(post), nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	userID, err := uuid.Parse(obj.AuthorID)
	if err != nil {
		return nil, apperr.Validation("INVALID_AUTHOR_ID", "invalid author id", map[string]any{
			"authorId": obj.AuthorID,
		})
	}

	u, err := r.UserSvc.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}

	return toUserModel(u), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := uuid.Parse(id)
	if err != nil {
		return nil, apperr.Validation("INVALID_POST_ID", "invalid post id", map[string]any{"id": id})
	}

	p, err := r.ContentQrySvc.GetPost(ctx, postID)
	if err != nil {
		return nil, err
	}

	return toPostModel(p), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	l, o := normalizePagination(limit, offset, 20, 100)

	f := contentApp.PostListFilter{Limit: l, Offset: o}
	posts, err := r.ContentQrySvc.ListPosts(ctx, f)
	if err != nil {
		return nil, err
	}

	return toPostModelList(posts), nil
}

// Post returns graph.PostResolver implementation.
func (r *Resolver) Post() graph.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
